-- =====================================================================
-- ミノル勤怠 (minoru-timecard) — 正典スキーマ（ベストエフォート復元版）
-- Backend: Supabase Postgres 17.x / RLS 有効
-- =====================================================================
--
-- ⚠️ 重要 / 推定を含む・実 DB と突合すること
-- ---------------------------------------------------------------------
-- ・本ファイルはベース初期スキーマの原本（supabase-schema.sql 相当）が
--   リポジトリに存在しないため、以下から「推定を含めて」復元したものです:
--     - ルートの差分 SQL (add-overtime-minutes / fix-*-.sql)
--     - フロントエンドの実クエリ (src/lib/*.ts)
--     - RPC/トリガー関数定義 (fix-search-path-security.sql)
--     - 診断 SQL (claudedocs/*.sql)
-- ・列の正確な型・DEFAULT・NOT NULL・FK・UNIQUE の一部は「推定」です。
--   本番 Supabase 実 DB と必ず突合してください（手順は docs/DATA_MODEL.md）。
-- ・"⚠️推定" コメントの付いた行は特に検証が必要な箇所です。
-- ・冪等性のため CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS /
--   DROP POLICY IF EXISTS 等を用いています。ただし RPC/トリガーは
--   CREATE OR REPLACE / DROP ... IF EXISTS で再適用可能にしています。
-- ・タイムゾーン規約: clock_in_time / clock_out_time は timestamptz(UTC保存)。
--   record_date は JST の暦日。work_start_time / work_end_time は JST の "HH:MM"。
-- =====================================================================

-- =====================================================================
-- 拡張
-- =====================================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid() 用（⚠️推定: 使用有無は要確認）

-- =====================================================================
-- 1. employees — 社員マスタ
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.employees (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ⚠️推定: TS では number。serial/identity のいずれか
    employee_id     text NOT NULL UNIQUE,          -- 業務キー（例 "001"）。time_records から参照される
    name            text NOT NULL,
    department      text,                           -- NULL 許容
    work_start_time text NOT NULL DEFAULT '09:00',  -- ⚠️推定: 型は text か time。JST "HH:MM"。診断SQLが ::time でキャストしている点から text の可能性が高い
    work_end_time   text NOT NULL DEFAULT '17:00',  -- ⚠️推定: 同上
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.employees IS '社員マスタ。個別の所定勤務時間を保持する。';
COMMENT ON COLUMN public.employees.employee_id     IS '業務上の社員ID（text, 例 "001"）。time_records.employee_id と対応。';
COMMENT ON COLUMN public.employees.work_start_time IS '所定始業時刻（JST, "HH:MM"）。';
COMMENT ON COLUMN public.employees.work_end_time   IS '所定終業時刻（JST, "HH:MM"）。';

-- =====================================================================
-- 2. time_records — 打刻記録
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.time_records (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ⚠️推定: TS では number
    employee_id      text NOT NULL,          -- employees.employee_id に対応（⚠️推定: 実FK制約の有無は要確認。退職者の孤児レコードが存在しうる）
    record_date      date NOT NULL,          -- JST の暦日
    clock_in_time    timestamptz,            -- 出勤（UTC保存）。NULL 可
    clock_out_time   timestamptz,            -- 退勤（UTC保存）。NULL 可
    status           text NOT NULL DEFAULT '通常',  -- 下記 CHECK 参照
    work_hours       numeric NOT NULL DEFAULT 0,    -- 実労働時間（時間）。昼休憩控除後
    overtime_minutes integer NOT NULL DEFAULT 0,    -- 残業（分）。add-overtime-minutes.sql で追加
    is_direct_work   boolean NOT NULL DEFAULT false, -- 直行直帰。true なら遅刻/早退/残業判定を無効化
    is_manual_entry  boolean NOT NULL DEFAULT false, -- ⚠️推定: 手動入力フラグ。getAllTimeRecords が参照
    approved_by      text,                   -- ⚠️推定: 承認者。型は text か uuid。getAllTimeRecords が参照
    notes            text,                   -- ⚠️推定: admin_create_time_record RPC のみが参照
    created_by_admin boolean NOT NULL DEFAULT false, -- ⚠️推定: admin_create_time_record RPC のみが参照
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),

    -- 退勤 > 出勤（負の勤務時間を禁止）。workTimeUtils の判定とも整合
    CONSTRAINT check_clock_times CHECK (
        clock_out_time IS NULL
        OR clock_in_time IS NULL
        OR clock_out_time > clock_in_time
    )
);

-- 1日1レコード。コード上「部分ユニーク索引」と表現されているため部分索引で復元。
-- ⚠️推定: 実 DB では通常の UNIQUE(employee_id, record_date) の可能性もある。要突合。
CREATE UNIQUE INDEX IF NOT EXISTS uq_time_records_employee_date
    ON public.time_records (employee_id, record_date);

-- 参照系クエリ用の索引（⚠️推定: 実在有無は要確認）
CREATE INDEX IF NOT EXISTS idx_time_records_record_date  ON public.time_records (record_date);
CREATE INDEX IF NOT EXISTS idx_time_records_employee_id  ON public.time_records (employee_id);

COMMENT ON TABLE  public.time_records IS '打刻記録。1社員・1日1レコード。';
COMMENT ON COLUMN public.time_records.clock_in_time    IS '出勤時刻（timestamptz, UTC保存）。';
COMMENT ON COLUMN public.time_records.clock_out_time   IS '退勤時刻（timestamptz, UTC保存）。';
COMMENT ON COLUMN public.time_records.overtime_minutes IS '残業時間（分）。退勤時刻 - 所定退勤時刻(work_end_time)。0以上。';
COMMENT ON COLUMN public.time_records.is_direct_work   IS '直行直帰。true の場合、遅刻/早退/残業判定を無効化し残業0とする。';

-- =====================================================================
-- 3. admin_profiles — 管理者プロファイル（Supabase Auth 連携）
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.admin_profiles (
    id                    uuid PRIMARY KEY,       -- = auth.users.id (auth.uid())
    name                  text,
    email                 text,                   -- ⚠️推定: handle_failed_login が email で検索するため存在
    role                  text NOT NULL DEFAULT 'admin', -- 'admin' | 'super_admin'（⚠️推定: 'viewer' は security.ts のみで言及）
    is_active             boolean NOT NULL DEFAULT true,
    failed_login_attempts integer NOT NULL DEFAULT 0,
    locked_until          timestamptz,            -- 5回失敗で now()+1h がセットされる
    last_login            timestamptz,            -- ⚠️推定: security.ts の型定義に存在
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT admin_profiles_role_check
        CHECK (role IN ('admin', 'super_admin', 'viewer')) -- ⚠️推定: 'viewer' の実在は要確認
    -- CONSTRAINT admin_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE -- ⚠️推定
);

COMMENT ON TABLE public.admin_profiles IS '管理者プロファイル。id は auth.users.id と一致。';

-- =====================================================================
-- 4. audit_logs — 監査ログ
-- =====================================================================
-- ⚠️重大な要突合ポイント:
--   ・トリガー関数 audit_trigger_function は old_data / new_data (json) に書き込む。
--   ・フロント (database.ts / security.ts) は old_values / new_values (+ reason,
--     ip_address, user_agent) に書き込む/読み取る。
--   両系統の列名が併存している可能性が高い。実 DB のカラム構成を必ず確認すること。
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ⚠️推定: TS では number
    table_name  text NOT NULL,
    record_id   text,          -- 例 "001-2026-05-27"（employee_id-record_date）または数値ID文字列
    action      text NOT NULL, -- 'INSERT' | 'UPDATE' | 'DELETE' | 'SELECT'
    old_data    jsonb,         -- audit_trigger_function が使用
    new_data    jsonb,         -- audit_trigger_function が使用
    old_values  jsonb,         -- ⚠️推定: フロントが使用（old_data と重複する可能性）
    new_values  jsonb,         -- ⚠️推定: フロントが使用（new_data と重複する可能性）
    user_id     uuid,          -- auth.uid()
    reason      text,          -- 修正理由（フロントが任意で付与。列が無い場合は new_values に格納するフォールバックあり）
    ip_address  text,          -- ⚠️推定
    user_agent  text,          -- ⚠️推定
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- fix-rls-performance.sql で idx_audit_logs_user_date を削除し、こちらを残す方針
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id_created
    ON public.audit_logs (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_table_name
    ON public.audit_logs (table_name);

COMMENT ON TABLE public.audit_logs IS '監査ログ。トリガー自動記録とフロント明示記録の両系統が書き込む。';

-- =====================================================================
-- 5. user_sessions — セッション管理
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.user_sessions (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(), -- ⚠️推定: 型/DEFAULT
    user_id       uuid NOT NULL,
    ip_address    text,
    user_agent    text,
    is_active     boolean NOT NULL DEFAULT true,
    expires_at    timestamptz NOT NULL,
    last_activity timestamptz DEFAULT now(),  -- ⚠️推定: security.ts の型定義に存在
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON public.user_sessions (user_id);

COMMENT ON TABLE public.user_sessions IS '管理者セッション。8時間有効・IP紐付け。cleanup_expired_sessions で失効管理。';

-- =====================================================================
-- 6. RLS 有効化
-- =====================================================================
ALTER TABLE public.employees      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_records   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_sessions  ENABLE ROW LEVEL SECURITY; -- ⚠️推定: 有効化されている前提

-- =====================================================================
-- 7. RLS ポリシー
--    最終状態は fix-rls-performance.sql（auth.uid() を (select auth.uid()) で
--    ラップ済み）を正とする。
-- =====================================================================

-- ---- employees --------------------------------------------------------
DROP POLICY IF EXISTS "public_employees_read"   ON public.employees;
DROP POLICY IF EXISTS "admin_employees_write"   ON public.employees;
DROP POLICY IF EXISTS "admin_employees_update"  ON public.employees;
DROP POLICY IF EXISTS "admin_employees_delete"  ON public.employees;

-- 読み取りは全員（anon 含む）許可 — タイムカードの社員選択のため
CREATE POLICY "public_employees_read" ON public.employees
    FOR SELECT USING (true);

CREATE POLICY "admin_employees_write" ON public.employees
    FOR INSERT WITH CHECK (
        (select auth.uid()) IS NOT NULL AND
        EXISTS (SELECT 1 FROM public.admin_profiles
                WHERE id = (select auth.uid()) AND is_active = true)
    );

CREATE POLICY "admin_employees_update" ON public.employees
    FOR UPDATE USING (
        (select auth.uid()) IS NOT NULL AND
        EXISTS (SELECT 1 FROM public.admin_profiles
                WHERE id = (select auth.uid()) AND is_active = true)
    );

CREATE POLICY "admin_employees_delete" ON public.employees
    FOR DELETE USING (
        (select auth.uid()) IS NOT NULL AND
        EXISTS (SELECT 1 FROM public.admin_profiles
                WHERE id = (select auth.uid()) AND is_active = true)
    );

-- ---- time_records -----------------------------------------------------
DROP POLICY IF EXISTS "public_time_records_read"   ON public.time_records;
DROP POLICY IF EXISTS "public_time_records_insert" ON public.time_records;
DROP POLICY IF EXISTS "public_time_records_update" ON public.time_records;
DROP POLICY IF EXISTS "admin_time_records_delete"  ON public.time_records;

-- 打刻の読み取り・追加・更新は認証なし（anon）でも可能。削除のみ管理者限定。
CREATE POLICY "public_time_records_read" ON public.time_records
    FOR SELECT USING (true);

CREATE POLICY "public_time_records_insert" ON public.time_records
    FOR INSERT WITH CHECK (true);

CREATE POLICY "public_time_records_update" ON public.time_records
    FOR UPDATE USING (true);

CREATE POLICY "admin_time_records_delete" ON public.time_records
    FOR DELETE USING (
        (select auth.uid()) IS NOT NULL AND
        EXISTS (SELECT 1 FROM public.admin_profiles
                WHERE id = (select auth.uid()) AND is_active = true)
    );

-- ---- admin_profiles ---------------------------------------------------
DROP POLICY IF EXISTS "admin_read"   ON public.admin_profiles;
DROP POLICY IF EXISTS "admin_insert" ON public.admin_profiles;
DROP POLICY IF EXISTS "admin_update" ON public.admin_profiles;

-- 自分のプロファイルのみ読み取り可
CREATE POLICY "admin_read" ON public.admin_profiles
    FOR SELECT USING (id = (select auth.uid()));

-- 追加はスーパー管理者のみ
CREATE POLICY "admin_insert" ON public.admin_profiles
    FOR INSERT WITH CHECK (
        EXISTS (SELECT 1 FROM public.admin_profiles
                WHERE id = (select auth.uid()) AND role = 'super_admin' AND is_active = true)
    );

-- 更新は本人またはスーパー管理者
CREATE POLICY "admin_update" ON public.admin_profiles
    FOR UPDATE USING (
        id = (select auth.uid()) OR
        EXISTS (SELECT 1 FROM public.admin_profiles
                WHERE id = (select auth.uid()) AND role = 'super_admin' AND is_active = true)
    );

-- ---- audit_logs -------------------------------------------------------
DROP POLICY IF EXISTS "audit_logs_insert" ON public.audit_logs;
DROP POLICY IF EXISTS "audit_logs_read"   ON public.audit_logs;

-- 挿入は認証済みユーザーのみ
CREATE POLICY "audit_logs_insert" ON public.audit_logs
    FOR INSERT WITH CHECK ((select auth.uid()) IS NOT NULL);

-- 読み取りは管理者のみ
CREATE POLICY "audit_logs_read" ON public.audit_logs
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.admin_profiles
                WHERE id = (select auth.uid()) AND is_active = true)
    );

-- ---- user_sessions ----------------------------------------------------
-- ⚠️推定: 実 DB のポリシー名/条件は未確認。本人セッションのみ操作可を仮定。
DROP POLICY IF EXISTS "user_sessions_self" ON public.user_sessions;
CREATE POLICY "user_sessions_self" ON public.user_sessions
    FOR ALL USING (user_id = (select auth.uid()))
    WITH CHECK (user_id = (select auth.uid()));

-- =====================================================================
-- 8. 関数（RPC / トリガー関数）
--    全て SET search_path = public でハードニング（fix-search-path-security.sql）。
-- =====================================================================

-- 8.1 updated_at 自動更新トリガー関数
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
SET search_path = public;

-- 8.2 監査ログ記録用トリガー関数
CREATE OR REPLACE FUNCTION public.audit_trigger_function()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.audit_logs (
        table_name, action, old_data, new_data, user_id, created_at
    )
    VALUES (
        TG_TABLE_NAME,
        TG_OP,
        CASE WHEN TG_OP = 'DELETE' OR TG_OP = 'UPDATE' THEN row_to_json(OLD) ELSE NULL END,
        CASE WHEN TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN row_to_json(NEW) ELSE NULL END,
        auth.uid(),
        NOW()
    );
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

-- 8.3 期限切れセッションのクリーンアップ
CREATE OR REPLACE FUNCTION public.cleanup_expired_sessions()
RETURNS void AS $$
BEGIN
    UPDATE public.user_sessions
       SET is_active = false
     WHERE expires_at < NOW() AND is_active = true;

    DELETE FROM public.user_sessions
     WHERE is_active = false AND created_at < NOW() - INTERVAL '30 days';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

-- 8.4 ログイン失敗処理（5回失敗で1時間ロック）
CREATE OR REPLACE FUNCTION public.handle_failed_login(user_email TEXT)
RETURNS void AS $$
BEGIN
    UPDATE public.admin_profiles
       SET failed_login_attempts = failed_login_attempts + 1,
           locked_until = CASE
               WHEN failed_login_attempts >= 5 THEN NOW() + INTERVAL '1 hour'
               ELSE locked_until
           END
     WHERE email = user_email;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

-- 8.5 管理者判定系
CREATE OR REPLACE FUNCTION public.check_admin_permissions()
RETURNS boolean AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.admin_profiles
         WHERE id = auth.uid() AND is_active = true
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

CREATE OR REPLACE FUNCTION public.is_admin_active()
RETURNS boolean AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.admin_profiles
         WHERE id = auth.uid() AND is_active = true
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

CREATE OR REPLACE FUNCTION public.is_admin_with_write_access()
RETURNS boolean AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.admin_profiles
         WHERE id = auth.uid()
           AND is_active = true
           AND role IN ('admin', 'super_admin')
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

-- 8.6 管理者による打刻作成
-- ⚠️注意: この RPC は p_employee_id を UUID として受け、time_records.employee_id
--         (text) に挿入する。実運用のフロントは呼び出しておらず、型不整合の疑い。
--         また notes / created_by_admin 列を参照する（time_records の推定列）。
CREATE OR REPLACE FUNCTION public.admin_create_time_record(
    p_employee_id  UUID,
    p_record_date  DATE,
    p_clock_in_time  TIMESTAMPTZ DEFAULT NULL,
    p_clock_out_time TIMESTAMPTZ DEFAULT NULL,
    p_notes TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_record_id UUID;
BEGIN
    IF NOT public.is_admin_with_write_access() THEN
        RAISE EXCEPTION 'Permission denied: Admin access required';
    END IF;

    INSERT INTO public.time_records (
        employee_id, record_date, clock_in_time, clock_out_time, notes, created_by_admin
    )
    VALUES (
        p_employee_id, p_record_date, p_clock_in_time, p_clock_out_time, p_notes, true
    )
    RETURNING id INTO v_record_id;

    RETURN v_record_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

-- 8.7 管理者による打刻削除
CREATE OR REPLACE FUNCTION public.admin_delete_time_record(p_record_id UUID)
RETURNS boolean AS $$
BEGIN
    IF NOT public.is_admin_with_write_access() THEN
        RAISE EXCEPTION 'Permission denied: Admin access required';
    END IF;

    DELETE FROM public.time_records WHERE id = p_record_id;
    RETURN FOUND;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

-- 8.8 打刻記録の原子的修正（delete + insert を単一トランザクションで）
-- ⚠️重大な推定: この関数の定義 SQL はリポジトリに存在しない。以下は
--   src/lib/database.ts の呼び出し（引数名・型・戻り値の id 参照）から復元した
--   ベストエフォート版。実 DB の定義と必ず突合すること。
--   ・p_employee_id は業務キー text（"001"）として渡される（UUID ではない）。
--   ・(employee_id, record_date) の既存行を削除し、新しい行を1件挿入して返す。
--   ・insert 失敗時は delete もロールバックされ、記録消失を防ぐ。
CREATE OR REPLACE FUNCTION public.correct_time_record(
    p_employee_id      TEXT,
    p_record_date      DATE,
    p_clock_in_time    TIMESTAMPTZ,
    p_clock_out_time   TIMESTAMPTZ,
    p_work_hours       NUMERIC,
    p_overtime_minutes INTEGER,
    p_status           TEXT,
    p_is_direct_work   BOOLEAN DEFAULT false
)
RETURNS public.time_records AS $$
DECLARE
    v_row public.time_records;
BEGIN
    -- 同一社員・同一日の既存レコードを削除
    DELETE FROM public.time_records
     WHERE employee_id = p_employee_id
       AND record_date = p_record_date;

    -- 新しいレコードを挿入
    INSERT INTO public.time_records (
        employee_id, record_date, clock_in_time, clock_out_time,
        work_hours, overtime_minutes, status, is_direct_work
    )
    VALUES (
        p_employee_id, p_record_date, p_clock_in_time, p_clock_out_time,
        p_work_hours, p_overtime_minutes, p_status, p_is_direct_work
    )
    RETURNING * INTO v_row;

    RETURN v_row;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;

-- =====================================================================
-- 9. トリガー
--    ⚠️推定: 実 DB での付与状況は要確認。fix-search-path-security.sql の
--            DROP FUNCTION ... CASCADE によりトリガーが失われた可能性がある。
-- =====================================================================

-- updated_at 自動更新
DROP TRIGGER IF EXISTS update_employees_updated_at ON public.employees;
CREATE TRIGGER update_employees_updated_at
    BEFORE UPDATE ON public.employees
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_time_records_updated_at ON public.time_records;
CREATE TRIGGER update_time_records_updated_at
    BEFORE UPDATE ON public.time_records
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_admin_profiles_updated_at ON public.admin_profiles;
CREATE TRIGGER update_admin_profiles_updated_at
    BEFORE UPDATE ON public.admin_profiles
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 監査トリガー（⚠️推定: どのテーブルに付いているかは要確認。time_records は有力）
DROP TRIGGER IF EXISTS audit_time_records ON public.time_records;
CREATE TRIGGER audit_time_records
    AFTER INSERT OR UPDATE OR DELETE ON public.time_records
    FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();

-- =====================================================================
-- 以上。推定箇所（⚠️推定 コメント）は docs/DATA_MODEL.md の突合手順で検証すること。
-- =====================================================================
</content>
