-- =============================================================================
-- ミノル勤怠（ミノルタイムカードシステム）Supabase スキーマ
-- =============================================================================
-- このファイルは 2026-07-06 に本番 Supabase プロジェクト（project_ref:
-- pddriyhmkvsklqmtxsro）を MCP 経由で読み取り、実測値に基づいて作成した
-- 「検証済みスキーマ」です。以前の推定復元版とは異なり、テーブル定義・制約・
-- RLS・関数は実 DB の定義そのものを反映しています。
--
-- 用途: 新規 Supabase プロジェクトを構築する際の基盤スキーマ。
--       既存本番は既に適用済みのため、本ファイルを本番へ流す必要はありません。
--
-- 2026-07-06 の整備で以下を本番へ適用済み（本ファイルも反映）:
--   * 残置バックアップ表 _recalc_backup_20260606 を削除（RLS無効の公開状態を解消）
--   * 壊れた未使用関数 admin_create_time_record / admin_delete_time_record を削除
--   * updated_at 自動更新トリガーを employees / time_records / admin_profiles に設置
--   * audit_trigger_function の列名を old_values / new_values に修正（トリガーは未設置）
--
-- 注意:
--   * (employee_id, record_date) の UNIQUE 制約は無い（1日1レコードはアプリ側で担保）。
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. テーブル
-- ---------------------------------------------------------------------------

-- 社員
CREATE TABLE IF NOT EXISTS public.employees (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     text NOT NULL UNIQUE,                 -- 業務キー（打刻・FK 参照先）
    name            text NOT NULL,
    department      text,
    work_start_time time DEFAULT '09:00:00',              -- 所定始業（JST の時刻）
    work_end_time   time DEFAULT '17:00:00',              -- 所定終業（JST の時刻）
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    is_active       boolean DEFAULT true,
    created_by      uuid,
    updated_by      uuid
);

-- 打刻記録
CREATE TABLE IF NOT EXISTS public.time_records (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      text NOT NULL REFERENCES public.employees(employee_id) ON DELETE CASCADE,
    record_date      date NOT NULL,                       -- JST の勤務日
    clock_in_time    timestamptz,                         -- UTC 保存
    clock_out_time   timestamptz,                         -- UTC 保存
    status           text DEFAULT '通常',
    work_hours       numeric DEFAULT 0,
    created_at       timestamptz DEFAULT now(),
    updated_at       timestamptz DEFAULT now(),
    ip_address       inet,
    user_agent       text,
    is_manual_entry  boolean DEFAULT false,
    approved_by      uuid,
    overtime_minutes integer NOT NULL DEFAULT 0,          -- 残業（分）= 退勤 - 所定終業、0以上
    is_direct_work   boolean NOT NULL DEFAULT false,      -- 直行・直帰（遅刻/早退/残業判定を無効化）
    CONSTRAINT time_records_status_check CHECK (
        status = ANY (ARRAY['通常','遅刻','早退','残業','遅刻・早退','遅刻・残業','設定エラー'])
    ),
    CONSTRAINT check_work_hours CHECK (work_hours >= 0 AND work_hours <= 24),
    CONSTRAINT check_clock_times CHECK (
        clock_out_time IS NULL OR clock_in_time IS NULL OR clock_out_time > clock_in_time
    )
);

COMMENT ON COLUMN public.time_records.overtime_minutes IS '残業時間（分）。退勤時刻 - 所定退勤時刻(work_end_time)。0以上。';
COMMENT ON COLUMN public.time_records.is_direct_work   IS '直行・直帰モードで打刻された記録か。trueの場合は遅刻/早退/残業の自動判定を無効化する。';

-- 管理者プロファイル（Supabase Auth と連携）
CREATE TABLE IF NOT EXISTS public.admin_profiles (
    id                    uuid PRIMARY KEY REFERENCES auth.users(id),
    name                  text,
    is_active             boolean DEFAULT true,
    created_at            timestamptz DEFAULT now(),
    updated_at            timestamptz DEFAULT now(),
    email                 text,
    role                  text DEFAULT 'viewer',
    last_login            timestamptz,
    failed_login_attempts integer DEFAULT 0,
    locked_until          timestamptz,
    CONSTRAINT check_admin_role CHECK (role = ANY (ARRAY['super_admin','admin','viewer']))
);

-- 監査ログ
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  text NOT NULL,
    record_id   text NOT NULL,
    action      text NOT NULL,
    old_values  jsonb,
    new_values  jsonb,
    user_id     uuid,
    ip_address  inet,
    user_agent  text,
    created_at  timestamptz DEFAULT now(),
    reason      text,
    CONSTRAINT audit_logs_action_check CHECK (action = ANY (ARRAY['INSERT','UPDATE','DELETE','SELECT']))
);

-- セッション管理
CREATE TABLE IF NOT EXISTS public.user_sessions (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL,
    ip_address    inet NOT NULL,
    user_agent    text,
    is_active     boolean DEFAULT true,
    expires_at    timestamptz NOT NULL,
    created_at    timestamptz DEFAULT now(),
    last_activity timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2. 関数（実 DB の定義を忠実に再現。SECURITY DEFINER + search_path=public）
-- ---------------------------------------------------------------------------

-- updated_at 自動更新用（※実 DB ではどのテーブルにもトリガー未設置）
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

-- 監査トリガー用関数（列名を実テーブルに合わせて修正済み。ただしトリガーは未設置）
CREATE OR REPLACE FUNCTION public.audit_trigger_function()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
    INSERT INTO public.audit_logs (
        table_name, record_id, action, old_values, new_values, user_id, created_at
    )
    VALUES (
        TG_TABLE_NAME,
        CASE WHEN TG_OP = 'DELETE' THEN (OLD.id)::text ELSE (NEW.id)::text END,
        TG_OP,
        CASE WHEN TG_OP = 'DELETE' OR TG_OP = 'UPDATE' THEN row_to_json(OLD)::jsonb ELSE NULL END,
        CASE WHEN TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN row_to_json(NEW)::jsonb ELSE NULL END,
        auth.uid(),
        NOW()
    );
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$function$;

-- 期限切れセッションの無効化・古いセッションの削除
CREATE OR REPLACE FUNCTION public.cleanup_expired_sessions()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
    UPDATE public.user_sessions
    SET is_active = false
    WHERE expires_at < NOW() AND is_active = true;

    DELETE FROM public.user_sessions
    WHERE is_active = false AND created_at < NOW() - INTERVAL '30 days';
END;
$function$;

-- ログイン失敗処理（5回以上で1時間ロック）
CREATE OR REPLACE FUNCTION public.handle_failed_login(user_email text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
    UPDATE public.admin_profiles
    SET
        failed_login_attempts = failed_login_attempts + 1,
        locked_until = CASE
            WHEN failed_login_attempts >= 5 THEN NOW() + INTERVAL '1 hour'
            ELSE locked_until
        END
    WHERE email = user_email;
END;
$function$;

-- 管理者権限チェック系
CREATE OR REPLACE FUNCTION public.check_admin_permissions()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.admin_profiles
        WHERE id = auth.uid() AND is_active = true
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin_active()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.admin_profiles
        WHERE id = auth.uid() AND is_active = true
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin_with_write_access()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.admin_profiles
        WHERE id = auth.uid() AND is_active = true
        AND role IN ('admin', 'super_admin')
    );
END;
$function$;

-- 打刻修正（原子的 delete+insert）。フロント（src/lib/database.ts）が使用する正規 RPC。
CREATE OR REPLACE FUNCTION public.correct_time_record(
    p_employee_id text, p_record_date date,
    p_clock_in_time timestamptz, p_clock_out_time timestamptz,
    p_work_hours numeric, p_overtime_minutes integer, p_status text,
    p_is_direct_work boolean DEFAULT false
)
RETURNS public.time_records
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_row public.time_records;
BEGIN
  DELETE FROM public.time_records
  WHERE employee_id = p_employee_id AND record_date = p_record_date;

  INSERT INTO public.time_records (
    employee_id, record_date, clock_in_time, clock_out_time,
    work_hours, overtime_minutes, status, is_direct_work, is_manual_entry
  ) VALUES (
    p_employee_id, p_record_date, p_clock_in_time, p_clock_out_time,
    p_work_hours, p_overtime_minutes, p_status, p_is_direct_work, true
  )
  RETURNING * INTO v_row;  -- 制約違反時は例外→DELETEも自動ロールバック

  RETURN v_row;
END;
$function$;

-- 注: 旧 admin_create_time_record / admin_delete_time_record（実テーブルと不整合で
--     壊れており、かつフロント未使用のデッドコード）は 2026-07-06 に削除済みのため
--     本スキーマには含めない。打刻修正は correct_time_record を使用する。

-- ---------------------------------------------------------------------------
-- 3. RLS 有効化
-- ---------------------------------------------------------------------------
ALTER TABLE public.employees      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_records   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_sessions  ENABLE ROW LEVEL SECURITY;  -- ※実 DB はポリシー未定義（API 経由アクセス不可・関数のみが操作）

-- ---------------------------------------------------------------------------
-- 4. RLS ポリシー（実 DB の定義を反映。auth.uid() は (select auth.uid()) でラップ済み）
-- ---------------------------------------------------------------------------

-- employees: 公開読み取り / 管理者のみ書き込み・削除
CREATE POLICY "public_employees_read" ON public.employees
    FOR SELECT USING (true);
CREATE POLICY "admin_employees_write" ON public.employees
    FOR INSERT WITH CHECK (
        (select auth.uid()) IS NOT NULL AND EXISTS (
            SELECT 1 FROM public.admin_profiles
            WHERE id = (select auth.uid()) AND is_active = true
        )
    );
CREATE POLICY "admin_employees_update" ON public.employees
    FOR UPDATE USING (
        (select auth.uid()) IS NOT NULL AND EXISTS (
            SELECT 1 FROM public.admin_profiles
            WHERE id = (select auth.uid()) AND is_active = true
        )
    );
CREATE POLICY "admin_employees_delete" ON public.employees
    FOR DELETE USING (
        (select auth.uid()) IS NOT NULL AND EXISTS (
            SELECT 1 FROM public.admin_profiles
            WHERE id = (select auth.uid()) AND is_active = true
        )
    );

-- time_records: キオスク設計（公開読み取り・追加・更新 / 管理者のみ削除）
CREATE POLICY "public_time_records_read" ON public.time_records
    FOR SELECT USING (true);
CREATE POLICY "public_time_records_insert" ON public.time_records
    FOR INSERT WITH CHECK (true);
CREATE POLICY "public_time_records_update" ON public.time_records
    FOR UPDATE USING (true);
CREATE POLICY "admin_time_records_delete" ON public.time_records
    FOR DELETE USING (
        (select auth.uid()) IS NOT NULL AND EXISTS (
            SELECT 1 FROM public.admin_profiles
            WHERE id = (select auth.uid()) AND is_active = true
        )
    );

-- admin_profiles: 自身の参照 / super_admin による作成・更新
CREATE POLICY "admin_read" ON public.admin_profiles
    FOR SELECT USING (id = (select auth.uid()));
CREATE POLICY "admin_insert" ON public.admin_profiles
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.admin_profiles admin_profiles_1
            WHERE admin_profiles_1.id = (select auth.uid())
              AND admin_profiles_1.role = 'super_admin'
              AND admin_profiles_1.is_active = true
        )
    );
CREATE POLICY "admin_update" ON public.admin_profiles
    FOR UPDATE USING (
        id = (select auth.uid()) OR EXISTS (
            SELECT 1 FROM public.admin_profiles admin_profiles_1
            WHERE admin_profiles_1.id = (select auth.uid())
              AND admin_profiles_1.role = 'super_admin'
              AND admin_profiles_1.is_active = true
        )
    );

-- audit_logs: 認証済みユーザーが追加 / 管理者が参照
CREATE POLICY "audit_logs_insert" ON public.audit_logs
    FOR INSERT WITH CHECK ((select auth.uid()) IS NOT NULL);
CREATE POLICY "audit_logs_read" ON public.audit_logs
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.admin_profiles
            WHERE id = (select auth.uid()) AND is_active = true
        )
    );

-- user_sessions: 実 DB はポリシー未定義（SECURITY DEFINER 関数のみが操作）。

-- ---------------------------------------------------------------------------
-- 5. updated_at 自動更新トリガー（2026-07-06 に本番へ設置済み）
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_employees_updated_at ON public.employees;
CREATE TRIGGER trg_employees_updated_at BEFORE UPDATE ON public.employees
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS trg_time_records_updated_at ON public.time_records;
CREATE TRIGGER trg_time_records_updated_at BEFORE UPDATE ON public.time_records
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS trg_admin_profiles_updated_at ON public.admin_profiles;
CREATE TRIGGER trg_admin_profiles_updated_at BEFORE UPDATE ON public.admin_profiles
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
